name: sallla_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
   sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  conditional_builder_null_safety: ^0.0.6
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  cached_network_image: ^3.2.3
  hexcolor: ^3.0.1
  shared_preferences: ^2.0.15
  webview_flutter_plus: ^0.3.0+2
  smooth_page_indicator: ^1.0.0+2
  fluttertoast: ^8.1.2
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
      - family: Jannah
        fonts:
          - asset: assets/fonts/arial.ttf
